### PR TITLE
Bump package versions

### PR DESCRIPTION
**Pull request by ThomasK33**

### CODE REVIEW

**Comment by florianreinhart** [comment]
We need to use our fork of node-http2. node-http2 is now officially deprecated and our fork includes required fixes for node-apn.

**Comment by florianreinhart** [comment]
I am not sure about the other dependencies.

@ThomasK33  have you tested this in any way?

**Comment by ThomasK33** [comment]
It's currently running on my dev system without any issues.

**Comment by wong2** [comment]
can we use the built in `http2` module and fallback to forked `node-http2`?

**Pull request closed without merging**
