### PR TITLE
Publish transpiled to npm

### PR DESCRIPTION
**Pull request by appfeel**
Hi, thanks for this module, very useful. I've written https://github.com/appfeel/node-pushnotifications which depends on `node-apn` among others.

I've seen that `node-apn` is published to npm in ES6. This pull request implements the following:
- Moved all ES6 files from `lib` to `src`
- Added `babel-cli` and `babel-preset-es2015` to dependencies
- Added a `build` script: `./node_modules/.bin/babel src -d lib`
- Added a `prepublish` script: `npm test && npm run build`
- Ran `npm run build`, which generates ES5 `lib`
- Added exclusions in `.npmignore` (doc, test, mock, src, not sure if all of them can be skipped to npm)
- Renamed variable in `notification/index.js:38`: `let headers = {};` to `let mHeaders = {}` (it was causing babel problems due to collision with function name)

This changes allows to develop in ES6 and publish to npm in ES5 compatible.

If you need something else to be changed (version increment, docs, etc.) just let me know. Hope this helps!

### CODE REVIEW

**Comment by appfeel** [comment]
Maybe an improvement would be to place index.js inside `/src` and create a new `index.js` like this:

```js
module.exports = require('./lib');
```

Imo it would be cleaner.

**Comment by florianreinhart** [comment]
Thanks @appfeel!

I am hesitant to merge this. What's the advantage of having ES5 support? Is it support for older node versions?

**Comment by miqmago** [comment]
Yes, basically it is support for old versions. As ES6 is not fully deployed everywhere, I'm still supporting ES5 in my modules, hope next year stopping doing this support for new projects, but this is my case :)

I've also seen that codacy complains basically for transpiled files. The ones in `src` files I can try to fix if needed.

**Comment by florianreinhart** [comment]
OK, thanks for explaining.

We currently require node v4 and IMHO it doesn't make sense to support node v0.10 and v0.12 anymore. This change would also complicate things. That's why I don't see any benefit. Are there other opinions?

**Comment by julien-c** [comment]
I'd vote for not supporting old versions of Node either.

**Comment by florianreinhart** [comment]
As there seems to be no one in favor of this I'll close the PR.

**Pull request closed without merging**
