### PR TITLE
Keep status code when 500 error occurs

### PR DESCRIPTION
**Pull request by zaumreit**

### CODE REVIEW

**Comment by oliversalzburg** [comment]
Could you squash your commits, please?

**Comment by zaumreit** [comment]
@oliversalzburg Done.

**Comment by oliversalzburg** [comment]
LGTM

**Comment by florianreinhart** [comment]
I am not sure about this change. The promise should either return an error object (in case of a connection error, etc.) or return an http status code.

As I understand it, if the APNs server returns an HTTP 500 the connection should be considered unusable. Sending additional requests will fail. This is probably a bug in the APNs backend. So in that case it is OK to return an error object as a workaround and close the stream.

**Comment by zaumreit** [comment]
In my case, we build a MSA to push notification for both iOS and Android and return the response and status code (defined by APNs and GCM) to client to get to know what happens and do something. So I think it would be better to return original message. :)

**Pull request closed without merging**
