### PR TITLE
#163, allow connection through HTTP proxy

### LINKED ISSUE #163: Proxy Mode
The current implementation does not allow usage of a proxy. This would be a great feature for those having to use node-apn behind firewalls. Are there any other suggestions on how use it in such an environment where internet access is restricted?

### PR DESCRIPTION
**Pull request by DaniJG**
This commit fixes #163, adding a proxy option to connect with APN servers using an HTTP proxy

### CODE REVIEW

**Comment by forty** [comment]
@florianreinhart do you know when this is going to be released on npm ? (I know I can install it right from github but I prefer sticking with the npm version if possible)
Thanks! (and thanks to @DaniJG - I did the same fix one day ago, but not as beautifully and without the tests ;))

**Comment by florianreinhart** [comment]
As soon as I create a new release 😄 Totally forgot about that...

**Comment by florianreinhart** [comment]
@forty this is now available in 2.2.0.

**Comment by alvarow** [comment]
Any reason this would stop working on v3 tree?

Thanks

**Pull request merged**
