### PR TITLE
Exposes Certificate Expiration Date

### PR DESCRIPTION
**Pull request by dplewis**
Hello,

This is my first PR. I need this for a Project that will send out a message when the certificate is about to expire.

Any help is appreciated.

### CODE REVIEW

**Comment by florianreinhart** [comment]
Thanks for your work on this, @dplewis.

To me this feels kind of hacky; putting the expiration date into the config and also that `validateCredentials()` returns the expiration date. I think you should extract the expiration date in you own code and handle it appropriately for your use case.

**Comment by dplewis** [comment]
@florianreinhart Thanks for the quick response. I agree this is a bit hacky, can you think of a cleaner way to implement this? I don't know much about the repo.

I know there are a lot of issues opened up about certificate expiry.

**Comment by dplewis** [comment]
@florianreinhart I added expiration date to the config because the config already contains data about the certificate.

I removed the return value from validateCredentials and added better tests.

**Comment by dplewis** [comment]
@florianreinhart How does this look?

**Pull request closed without merging**
