### PR TITLE
HTTP2 Keep Alive

### PR DESCRIPTION
**Pull request by oliversalzburg**
Cherry-picked from @Discountrobot's fork.
Related: #449
Related: #451 
Related: #454

### CODE REVIEW

**Comment by florianreinhart** [comment]
@oliversalzburg Thanks for fixing the style issues.
We should also keep the test coverage at 100%. Could you take a look at that?

**Comment by oliversalzburg** [comment]
Yeah, I'll try to provide that as well. I just have to familiarize myself with the codebase and find some free time ;D

**Comment by oliversalzburg** [comment]
@Discountrobot Awesome! Thanks. I updated the PR with your latest changes.

**Comment by menelike** [comment]
Thanks for this fix, unfortunately this doesn't solve the issue in our case, still getting:

```
{
    "device": "DEVICE_ID_FOO_BAR",
    "error": {
      "jse_shortmsg": "apn write failed",
      "jse_cause": { "code": "ETIMEDOUT", "errno": "ETIMEDOUT", "syscall": "read" },
      "jse_info": {},
      "message": "apn write failed: read ETIMEDOUT"
    }
  }
```

**Comment by menelike** [comment]
@Discountrobot 

1. Token Based
2. Production

We're using `2.1.2` (and this branch as a fix) in context of docker containers on Azure, ubuntu 14.04 and [npm 4.6.1](https://hub.docker.com/r/library/node/tags/4.6.1/)

* `Linux fooNode 3.19.0-65-generic #73~14.04.1-Ubuntu SMP Wed Jun 29 21:05:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

* `Docker version 1.11.2, build b9f10c9`

In difference to `2.1.2` it seems that this branch works again after a certain point. I'll try the 1.x branch in contrast this week.

**Comment by n3trino** [comment]
Is this PR merged to master? we need this fix

**Comment by florianreinhart** [comment]
@oliversalzburg can we close this PR, if we merge #480?

**Comment by oliversalzburg** [comment]
@florianreinhart  Gladly :) Please close it whenever you see fit.

**Pull request closed without merging**
